export const messagesEn = {
  common: {
    menu: "Menu", mainNavigation: "Main navigation", searchCompanies: "Search companies", searchUnavailable: "Search unavailable", searchHint: "Search ticker or company  ( / )",
    language: "Language", spanish: "Spanish", english: "English", loading: "Loading…", retry: "Retry", notFound: "Not found", all: "All", never: "never",
    market: "Market", sector: "Sector", industry: "Industry", industries: "Industries", company: "Company", index: "Index", subIndustry: "Sub-industry", companies: "Companies", sectors: "Sectors", countries: "Countries", drivers: "Drivers", period: "period", days: "days", events: "events", articles: "articles", claims: "claims", evidenceItems: "evidence items",
    realData: "Real data", demoData: "Demo data", partialData: "Partial data", official: "Official", inferred: "Inferred", direct: "Direct", related: "Related", sourceBased: "Source based", unknown: "Unknown", notAvailable: "Not available", noData: "No data", noResults: "No results", calculatedByMarketRadar: "Calculated by MarketRadar",
    positive: "Positive", negative: "Negative", mixed: "Mixed", upwardPressure: "Upward pressure", downwardPressure: "Downward pressure", developing: "Developing", active: "Active", stale: "Older", high: "High", medium: "Medium", low: "Low",
  },
  navigation: {
    dashboard: "Dashboard", global: "Global", world: "World", commodities: "Commodities", worldPulse: "World Pulse", markets: "Markets", sectors: "Sectors", companies: "Companies", tools: "Tools", screener: "Screener", compare: "Compare", watchlist: "Watchlist", ask: "Ask MarketRadar", availableInPhase: "Available in Phase {phase}", footer: "Phase 2B · SEC fundamentals · Alpaca EOD · free data",
  },
  market: {
    marketData: "Market data", topGainers: "Top gainers", topLosers: "Top losers", mostActive: "Most active", relativeVolume: "Relative volume", highestRsi: "Highest RSI", lowestRsi: "Lowest RSI", week52Highs: "52-week highs", week52Lows: "52-week lows", breadth: "Breadth", performance: "Performance", marketCap: "Market cap", price: "Price", volume: "Volume", symbol: "Symbol", ticker: "Ticker", exchange: "Exchange", currency: "Currency", average: "average", highestReturn: "Highest return over {range}", lowestReturn: "Lowest return over {range}", dollarVolume: "Highest dollar volume in the last session", volumeVsAverage: "Volume vs 20-session average", new52High: "Trading at a new 52-week high", new52Low: "Trading at a new 52-week low", constituents: "constituents", constituentsNotTracked: "Constituents not tracked yet", noSecuritiesMatch: "No securities match", noRankingMatches: "No member meets this ranking's criteria for the selected period.", add: "Added", range: "Range", chart: "Chart", marketStatusDemo: "No synced market data: prices, lists, heatmaps and rankings are simulated (DEMO). Reference data is real.", endOfDayPrices: "End-of-day prices from {provider} (as of {date}); returns, indicators, breadth and aggregates are calculated by MarketRadar.", missingRemainder: "; the rest are shown as missing", benchmarkDemo: "Benchmark strip (indices, VIX, DXY, commodities, rates) is still DEMO.",
  },
  company: {
    overview: "Overview", financials: "Financials", valuation: "Valuation", technical: "Technical", news: "News", earnings: "Earnings", peers: "Peers", ai: "AI", keyMetrics: "Key metrics", identity: "Identity", about: "About", headquarters: "Headquarters", founded: "Founded", employees: "Employees", website: "Website", noDescription: "No company description yet", descriptionSource: "Descriptions, employees and logos come from the company profile provider.", noPeers: "No peers in the current universe", peersDefinition: "Peers are companies with the same sub-industry (or industry) classification.", companySections: "Company sections", noFinancialStatements: "No official financial statements synced for this company yet", noFundamentals: "No official fundamentals synced for this company yet", noPriceHistory: "No real price history synced for this security yet", noEarnings: "No official results synced for this company yet", reportedResults: "Reported results", estimateDates: "Estimates & upcoming dates", quarter: "Quarter", periodEnd: "Period end", revenue: "Revenue", grossProfit: "Gross profit", operatingIncome: "Operating income", netIncome: "Net income", freeCashFlow: "Free cash flow", cash: "Cash & equivalents", debt: "Total debt", assets: "Total assets", liabilities: "Total liabilities", equity: "Total equity", revenueGrowth: "Revenue growth", operatingCashFlow: "Operating cash flow", capitalExpenditure: "Capital expenditure", netIncomeCommon: "Net income to common", weightedSharesBasic: "Weighted avg. shares (basic)", weightedSharesDiluted: "Weighted avg. shares (diluted)", epsBasic: "EPS (basic)", epsDiluted: "EPS (diluted)", pretaxIncome: "Pre-tax income", incomeTaxExpense: "Income tax expense", depreciationAmortization: "Depreciation & amortization", dividendsPerShare: "Dividends declared per share", sharesOutstanding: "Shares outstanding", incomeStatement: "Income statement", balanceSheet: "Balance sheet", cashFlow: "Cash flow", annual: "Annual", quarterly: "Quarterly", ttm: "TTM", periodsUnavailable: "No periods available", itemsUnavailable: "Items not available from filings", methodology: "Methodology", valuationRatios: "Valuation ratios", technicalIndicators: "Technical indicators", noPeersDescription: "Peers are companies with the same sub-industry (or industry) classification.",
  },
  technical: {
    relativeVolume: "Relative volume", week52High: "52-week high", week52Low: "52-week low", noUnusualMove: "No unusual move", aboveEma: "Above EMA", belowEma: "Below EMA", market: "Market", sectorExcess: "Sector excess", industryExcess: "Industry excess", companySpecific: "Company specific", notEnoughHistory: "Not enough history", calculatedFromOhlcv: "Calculated by MarketRadar from daily OHLCV with pure, tested functions.",
  },
  news: {
    topEvents: "Top events", event: "Event", macro: "Macro", geopolitics: "Geopolitics", regulation: "Regulation", technology: "Technology", whatWorldTalking: "What the world is talking about", eventFamilies: "Event families", sources: "Sources", sourceStatus: "status · free, no keys", noEvents: "No events in this view yet", relatedEvents: "No related events in the last 7 days.", noRelatedImpacts: "No potential impacts from recent events", globalIntelligenceUnavailable: "Global intelligence is not connected yet", potentialImpacts: "potential impacts on {name} · 7 days", globalContext: "World context", noNewsSource: "No news source connected", verifiedNewsWillAppear: "Verified, deduplicated news linked to this entity will appear here.", newsAndEvents: "News & events", independentReports: "Independent reports = distinct publishers with their own wording (syndicated copies count once)", sourcesDisagree: "Sources disagree", reportsUnnamed: "All reports cite unnamed sources", developingHint: "Developing: first seen < 6 h ago · Active: new articles in the last 48 h · Older: no new coverage for 48 h", potentialRelationships: "Potential relationships inferred by MarketRadar — not predictions", curatedGraph: "Potential relationships from MarketRadar's curated mechanism graph — not predictions.", officialSource: "Official source", unconfirmed: "Unconfirmed", horizon: "Horizon", marketDataHint: "Real market data (MarketRadar): last session return of the entities named in the event", directMentions: "direct mentions · 7 days", worldPulse: "World Pulse", firstSeen: "First seen", lastUpdate: "last update", originalLanguage: "Original language", originalHeadline: "Original headline", originalContent: "Showing the source headline in its original language.",
  },
  intelligence: {
    answer: "Answer", claimsEvidence: "Claims & evidence", provider: "Intelligence provider", legend: "Legend", deterministicEngine: "Deterministic engine", deterministicTitle: "Composed by MarketRadar's deterministic engine — no AI involved", aiValidated: "AI · validated", understood: "Understood:", potentialImpactsEntity: "Potential impacts on the entity", catalysts: "Catalysts in the window", noClaims: "No claims.", additiveDecomposition: "Additive decomposition of the return", relVolume: "rel. volume", source: "Source", mechanism: "Mechanism", horizon: "Horizon", confidence: "confidence", learningMode: "Learning mode", formula: "Formula:", howToRead: "How to read it:", caveat: "Caveat:", withRealData: "With {ticker}'s real data", market1d: "Market 1D", priceEarnings: "Price / Earnings", priceSales: "Price / Sales", priceBook: "Price / Book", evEbitda: "EV / EBITDA",
  },
  ask: {
    title: "Ask MarketRadar", question: "Question", askButton: "Ask", examples: ["Why is NVIDIA falling?", "What is happening with copper miners?", "What news is affecting Technology?", "What changed in the market today?"], help: "MarketRadar first understands the question and retrieves its own data (prices, fundamentals, events, relationship graph); only then does it compose an answer. Every figure comes from MarketRadar; every claim is labelled. Not investment advice.", claimsCited: "claims cite evidence (the rest are explicit UNKNOWNs).", aiEnabled: "OpenAI enabled", deterministic: "Deterministic", aiSkipped: "AI skipped", rejectedClaims: "AI claim(s) rejected by grounding validation.", noSyncedMarketData: "No real price data", period: "period", learningFormula: "Formula: ", howToRead: "How to read it: ", askSpanishSample: "¿Por qué está cayendo NVIDIA? · ¿Qué pasa con los mineros de cobre? · ¿Qué afecta a Tecnología?", askEnglishSample: "Why is NVIDIA falling? · What is happening with copper miners? · What is affecting Technology?",
  },
  states: {
    noCompaniesMatch: "No companies match these filters", differentSearch: "Try a different search term or clear the filters.", tickerOrName: "Ticker or name", allSectors: "All sectors", allTracked: "All tracked", pagination: "Pagination", couldNotLoad: "Could not load this view", dataLayerDown: "The data layer did not respond. In local development, check that Supabase is running and that .env.local exists.", dataErrorTitle: "Market data unavailable", dataErrorDescription: "MarketRadar could not read its data. Please retry; in local development, check the database connection.", configurationErrorTitle: "Configuration needed", configurationErrorDescription: "A required server setting is missing or invalid. Check the MarketRadar server configuration.", renderErrorTitle: "This view could not be displayed", renderErrorDescription: "An application error occurred while displaying this view. Please retry.", notFoundDescription: "This market, sector, industry or company is not in the MarketRadar universe.", browseCompanies: "Browse companies",
  },
} as const;

type Widen<T> = { [K in keyof T]: T[K] extends string ? string : T[K] extends readonly string[] ? readonly string[] : Widen<T[K]> };

export const messagesEs: Widen<typeof messagesEn> = {
  common: {
    menu: "Menú", mainNavigation: "Navegación principal", searchCompanies: "Buscar empresas", searchUnavailable: "Búsqueda no disponible", searchHint: "Buscar ticker o empresa  ( / )",
    language: "Idioma", spanish: "Español", english: "Inglés", loading: "Cargando…", retry: "Reintentar", notFound: "No encontrado", all: "Todos", never: "nunca",
    market: "Mercado", sector: "Sector", industry: "Industria", industries: "Industrias", company: "Empresa", index: "Índice", subIndustry: "Subindustria", companies: "Empresas", sectors: "Sectores", countries: "Países", drivers: "Factores", period: "periodo", days: "días", events: "eventos", articles: "artículos", claims: "afirmaciones", evidenceItems: "elementos de evidencia",
    realData: "Datos reales", demoData: "Datos de demostración", partialData: "Datos parciales", official: "Oficial", inferred: "Inferido", direct: "Directo", related: "Relacionado", sourceBased: "Basado en fuentes", unknown: "Desconocido", notAvailable: "No disponible", noData: "Sin datos", noResults: "Sin resultados", calculatedByMarketRadar: "Calculado por MarketRadar",
    positive: "Positivo", negative: "Negativo", mixed: "Mixto", upwardPressure: "Presión alcista", downwardPressure: "Presión bajista", developing: "En desarrollo", active: "Activo", stale: "Anterior", high: "Alta", medium: "Media", low: "Baja",
  },
  navigation: {
    dashboard: "Panel", global: "Global", world: "Mundo", commodities: "Materias primas", worldPulse: "Pulso global", markets: "Mercados", sectors: "Sectores", companies: "Empresas", tools: "Herramientas", screener: "Filtro", compare: "Comparar", watchlist: "Seguimiento", ask: "Pregunta a MarketRadar", availableInPhase: "Disponible en la fase {phase}", footer: "Fase 2B · Fundamentales SEC · Alpaca EOD · datos gratuitos",
  },
  market: {
    marketData: "Datos de mercado", topGainers: "Mayores subidas", topLosers: "Mayores caídas", mostActive: "Más activos", relativeVolume: "Volumen relativo", highestRsi: "RSI más alto", lowestRsi: "RSI más bajo", week52Highs: "Máximos de 52 semanas", week52Lows: "Mínimos de 52 semanas", breadth: "Amplitud", performance: "Rendimiento", marketCap: "Capitalización bursátil", price: "Precio", volume: "Volumen", symbol: "Símbolo", ticker: "Ticker", exchange: "Bolsa", currency: "Divisa", average: "media", highestReturn: "Mayor rendimiento en {range}", lowestReturn: "Menor rendimiento en {range}", dollarVolume: "Mayor volumen negociado en la última sesión", volumeVsAverage: "Volumen frente a la media de 20 sesiones", new52High: "En un nuevo máximo de 52 semanas", new52Low: "En un nuevo mínimo de 52 semanas", constituents: "componentes", constituentsNotTracked: "Aún no se siguen sus componentes", noSecuritiesMatch: "Ningún valor coincide", noRankingMatches: "Ningún componente cumple los criterios de esta clasificación para el periodo seleccionado.", add: "Añadido", range: "Rango", chart: "Gráfico", marketStatusDemo: "Sin datos de mercado sincronizados: precios, listas, mapas de calor y clasificaciones son simulados (DEMO). Los datos de referencia son reales.", endOfDayPrices: "Precios de cierre de {provider} (a fecha de {date}); MarketRadar calcula rendimientos, indicadores, amplitud y agregados.", missingRemainder: "; el resto figura como sin datos", benchmarkDemo: "La franja de referencias (índices, VIX, DXY, materias primas y tipos) sigue en DEMO.",
  },
  company: {
    overview: "Resumen", financials: "Finanzas", valuation: "Valoración", technical: "Técnico", news: "Noticias", earnings: "Resultados", peers: "Comparables", ai: "IA", keyMetrics: "Métricas clave", identity: "Identidad", about: "Acerca de", headquarters: "Sede", founded: "Fundación", employees: "Empleados", website: "Sitio web", noDescription: "Aún no hay descripción de la empresa", descriptionSource: "Las descripciones, la plantilla y los logotipos proceden del proveedor del perfil de empresa.", noPeers: "No hay comparables en el universo actual", peersDefinition: "Son comparables las empresas de la misma subindustria (o industria).", companySections: "Secciones de empresa", noFinancialStatements: "Aún no se han sincronizado estados financieros oficiales de esta empresa", noFundamentals: "Aún no se han sincronizado datos fundamentales oficiales de esta empresa", noPriceHistory: "Aún no hay historial de precios reales sincronizado para este valor", noEarnings: "Aún no se han sincronizado resultados oficiales de esta empresa", reportedResults: "Resultados publicados", estimateDates: "Estimaciones y próximas fechas", quarter: "Trimestre", periodEnd: "Fin del periodo", revenue: "Ingresos", grossProfit: "Beneficio bruto", operatingIncome: "Resultado operativo", netIncome: "Beneficio neto", freeCashFlow: "Flujo de caja libre", cash: "Efectivo y equivalentes", debt: "Deuda total", assets: "Activos totales", liabilities: "Pasivos totales", equity: "Patrimonio neto", revenueGrowth: "Crecimiento de ingresos", operatingCashFlow: "Flujo de caja operativo", capitalExpenditure: "Inversión en capital", netIncomeCommon: "Beneficio neto atribuible a ordinarias", weightedSharesBasic: "Acciones medias ponderadas (básicas)", weightedSharesDiluted: "Acciones medias ponderadas (diluidas)", epsBasic: "BPA (básico)", epsDiluted: "BPA (diluido)", pretaxIncome: "Beneficio antes de impuestos", incomeTaxExpense: "Gasto por impuestos", depreciationAmortization: "Depreciación y amortización", dividendsPerShare: "Dividendos declarados por acción", sharesOutstanding: "Acciones en circulación", incomeStatement: "Cuenta de resultados", balanceSheet: "Balance", cashFlow: "Flujo de caja", annual: "Anual", quarterly: "Trimestral", ttm: "Últimos 12 meses", periodsUnavailable: "No hay periodos disponibles", itemsUnavailable: "Partidas no disponibles en los informes", methodology: "Metodología", valuationRatios: "Ratios de valoración", technicalIndicators: "Indicadores técnicos", noPeersDescription: "Son comparables las empresas de la misma subindustria (o industria).",
  },
  technical: {
    relativeVolume: "Volumen relativo", week52High: "Máximo de 52 semanas", week52Low: "Mínimo de 52 semanas", noUnusualMove: "Sin movimiento inusual", aboveEma: "Por encima de EMA", belowEma: "Por debajo de EMA", market: "Mercado", sectorExcess: "Exceso frente al sector", industryExcess: "Exceso frente a la industria", companySpecific: "Específico de la empresa", notEnoughHistory: "Historial insuficiente", calculatedFromOhlcv: "Calculado por MarketRadar a partir de datos OHLCV diarios con funciones probadas.",
  },
  news: {
    topEvents: "Eventos destacados", event: "Evento", macro: "Macro", geopolitics: "Geopolítica", regulation: "Regulación", technology: "Tecnología", whatWorldTalking: "De qué habla el mundo", eventFamilies: "Familias de eventos", sources: "Fuentes", sourceStatus: "estado · gratis y sin claves", noEvents: "Aún no hay eventos en esta vista", relatedEvents: "No hay eventos relacionados en los últimos 7 días.", noRelatedImpacts: "No hay impactos potenciales de eventos recientes", globalIntelligenceUnavailable: "La inteligencia global aún no está conectada", potentialImpacts: "impactos potenciales en {name} · 7 días", globalContext: "Contexto global", noNewsSource: "No hay una fuente de noticias conectada", verifiedNewsWillAppear: "Aquí aparecerán noticias verificadas y deduplicadas relacionadas con esta entidad.", newsAndEvents: "Noticias y eventos", independentReports: "Los informes independientes proceden de editores distintos con redacción propia (las copias sindicadas cuentan una sola vez)", sourcesDisagree: "Las fuentes discrepan", reportsUnnamed: "Todos los informes citan fuentes anónimas", developingHint: "En desarrollo: detectado hace < 6 h · Activo: artículos nuevos en las últimas 48 h · Anterior: sin cobertura nueva durante 48 h", potentialRelationships: "Relaciones potenciales inferidas por MarketRadar; no son predicciones", curatedGraph: "Relaciones potenciales del grafo de mecanismos de MarketRadar; no son predicciones.", officialSource: "Fuente oficial", unconfirmed: "Sin confirmar", horizon: "Horizonte", marketDataHint: "Datos de mercado reales (MarketRadar): rendimiento de la última sesión de las entidades citadas en el evento", directMentions: "menciones directas · 7 días", worldPulse: "Pulso global", firstSeen: "Primera detección", lastUpdate: "última actualización", originalLanguage: "Idioma original", originalHeadline: "Titular original", originalContent: "Se muestra el titular de la fuente en su idioma original.",
  },
  intelligence: {
    answer: "Respuesta", claimsEvidence: "Afirmaciones y evidencia", provider: "Proveedor de inteligencia", legend: "Leyenda", deterministicEngine: "Motor determinista", deterministicTitle: "Redactado por el motor determinista de MarketRadar, sin IA", aiValidated: "IA · validada", understood: "Entendido:", potentialImpactsEntity: "Impactos potenciales en la entidad", catalysts: "Catalizadores del periodo", noClaims: "Sin afirmaciones.", additiveDecomposition: "Descomposición aditiva del rendimiento", relVolume: "vol. relativo", source: "Fuente", mechanism: "Mecanismo", horizon: "Horizonte", confidence: "confianza", learningMode: "Modo de aprendizaje", formula: "Fórmula:", howToRead: "Cómo interpretarlo:", caveat: "Advertencia:", withRealData: "Con datos reales de {ticker}", market1d: "Mercado 1D", priceEarnings: "Precio / Beneficio", priceSales: "Precio / Ventas", priceBook: "Precio / Valor contable", evEbitda: "EV / EBITDA",
  },
  ask: {
    title: "Pregunta a MarketRadar", question: "Pregunta", askButton: "Preguntar", examples: ["¿Por qué está cayendo NVIDIA?", "¿Qué pasa con los mineros de cobre?", "¿Qué noticias afectan a Tecnología?", "¿Qué ha cambiado hoy en el mercado?"], help: "MarketRadar primero interpreta la pregunta y consulta sus propios datos (precios, fundamentales, eventos y grafo de relaciones); después redacta la respuesta. Todas las cifras proceden de MarketRadar y cada afirmación está etiquetada. No es asesoramiento de inversión.", claimsCited: "afirmaciones citan evidencia (el resto son DESCONOCIDOS explícitos).", aiEnabled: "OpenAI activado", deterministic: "Determinista", aiSkipped: "IA omitida", rejectedClaims: "Afirmación(es) de IA rechazadas por la validación de evidencia.", noSyncedMarketData: "Sin datos de precios reales", period: "periodo", learningFormula: "Fórmula: ", howToRead: "Cómo interpretarlo: ", askSpanishSample: "¿Por qué está cayendo NVIDIA? · ¿Qué pasa con los mineros de cobre? · ¿Qué afecta a Tecnología?", askEnglishSample: "Why is NVIDIA falling? · What is happening with copper miners? · What is affecting Technology?",
  },
  states: {
    noCompaniesMatch: "Ninguna empresa coincide con estos filtros", differentSearch: "Prueba otra búsqueda o borra los filtros.", tickerOrName: "Ticker o nombre", allSectors: "Todos los sectores", allTracked: "Todos los seguidos", pagination: "Paginación", couldNotLoad: "No se pudo cargar esta vista", dataLayerDown: "La capa de datos no respondió. En desarrollo local, comprueba que Supabase esté iniciado y que exista .env.local.", dataErrorTitle: "Datos de mercado no disponibles", dataErrorDescription: "MarketRadar no pudo leer sus datos. Reintenta; en desarrollo local, comprueba la conexión con la base de datos.", configurationErrorTitle: "Configuración necesaria", configurationErrorDescription: "Falta un ajuste obligatorio del servidor o su valor es incorrecto. Revisa la configuración de MarketRadar.", renderErrorTitle: "No se pudo mostrar esta vista", renderErrorDescription: "Se produjo un error de la aplicación al mostrar esta vista. Reintenta.", notFoundDescription: "Este mercado, sector, industria o empresa no está en el universo de MarketRadar.", browseCompanies: "Explorar empresas",
  },
};

export type MessageCatalog = typeof messagesEn;
export type Locale = "es" | "en";
export const DEFAULT_LOCALE: Locale = "es";
export const SUPPORTED_LOCALES = ["es", "en"] as const satisfies readonly Locale[];

export function normalizeLocale(value: unknown): Locale {
  return value === "en" ? "en" : "es";
}

export function getMessages(locale: Locale): MessageCatalog {
  return locale === "es" ? (messagesEs as MessageCatalog) : messagesEn;
}

export function interpolate(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{([a-zA-Z][\w]*)\}/g, (match, key: string) => String(values[key] ?? match));
}

export function enumLabel(locale: Locale, value: string): string {
  const labels: Record<string, string> = {
    potential_positive: locale === "es" ? "Posible impacto positivo" : "Potential positive impact",
    potential_negative: locale === "es" ? "Posible impacto negativo" : "Potential negative impact",
    mixed_uncertain: locale === "es" ? "Mixto o incierto" : "Mixed or uncertain",
    developing: locale === "es" ? "En desarrollo" : "Developing",
    active: locale === "es" ? "Activo" : "Active",
    stale: locale === "es" ? "Anterior" : "Older",
    days: locale === "es" ? "días" : "days",
    weeks: locale === "es" ? "semanas" : "weeks",
    months: locale === "es" ? "meses" : "months",
    quarters: locale === "es" ? "trimestres" : "quarters",
    DIRECT: locale === "es" ? "Directo" : "Direct",
    SECOND_ORDER: locale === "es" ? "Segundo orden" : "Second order",
    MACRO: locale === "es" ? "Macro" : "Macro",
    SUPPLY_CHAIN: locale === "es" ? "Cadena de suministro" : "Supply chain",
    official: locale === "es" ? "Oficial" : "Official",
    regulator: locale === "es" ? "Regulador" : "Regulator",
    company_filing: locale === "es" ? "Informe de empresa" : "Company filing",
    media: locale === "es" ? "Medio" : "Media",
    aggregator: locale === "es" ? "Agregador" : "Aggregator",
  };
  return labels[value] ?? value;
}
