/**
 * Alias de empresas curados (complementan los generados automáticamente desde el nombre en la base).
 *
 *   add        alias adicionales seguros (marcas, nombres cortos habituales en prensa)
 *   ambiguous  alias que también son palabras comunes, apellidos o lugares: solo cuentan con contexto
 *              de empresa en el texto (shares, earnings, CEO…) o con el ticker
 *   block      alias generados que NUNCA deben usarse
 */
export interface AliasOverride {
  add?: string[];
  /** Marcas/productos de la empresa (YouTube, AWS, WhatsApp): relación real pero indirecta ⇒ confianza 0.7. */
  brands?: string[];
  ambiguous?: string[];
  block?: string[];
}

export const COMPANY_ALIAS_OVERRIDES: Readonly<Record<string, AliasOverride>> = {
  AAPL: { add: ["Apple"] },
  GOOGL: { add: ["Google", "Alphabet"], brands: ["YouTube", "Waymo", "DeepMind"] },
  META: { add: ["Meta", "Meta Platforms"], brands: ["Facebook", "Instagram", "WhatsApp"] },
  MSFT: { add: ["Microsoft"], brands: ["Azure", "LinkedIn", "GitHub"] },
  AMZN: { add: ["Amazon", "Amazon Web Services"], brands: ["AWS", "Whole Foods"] },
  NVDA: { add: ["Nvidia", "NVIDIA"] },
  TSLA: { add: ["Tesla"] },
  "BRK.B": { add: ["Berkshire Hathaway", "Berkshire"] },
  JPM: { add: ["JPMorgan", "JP Morgan", "J.P. Morgan", "JPMorgan Chase"] },
  BAC: { add: ["Bank of America", "BofA"] },
  C: { add: ["Citigroup", "Citi"] },
  GS: { add: ["Goldman Sachs", "Goldman"] },
  MS: { add: ["Morgan Stanley"] },
  WFC: { add: ["Wells Fargo"] },
  SCHW: { add: ["Charles Schwab", "Schwab"] },
  BLK: { add: ["BlackRock"] },
  BX: { add: ["Blackstone"] },
  KKR: { add: ["KKR"] },
  APO: { add: ["Apollo Global"], ambiguous: ["Apollo"] },
  AXP: { add: ["American Express", "Amex"] },
  V: { add: ["Visa Inc"], ambiguous: ["Visa"] },
  MA: { add: ["Mastercard"] },
  PYPL: { add: ["PayPal"] },
  COIN: { add: ["Coinbase"] },
  HOOD: { add: ["Robinhood"] },
  WMT: { add: ["Walmart"] },
  COST: { add: ["Costco"] },
  TGT: { add: ["Target Corp", "Target Corporation"], ambiguous: ["Target"] },
  HD: { add: ["Home Depot"] },
  LOW: { add: ["Lowe's"] },
  MCD: { add: ["McDonald's", "McDonalds"], ambiguous: ["McDonald"] },
  SBUX: { add: ["Starbucks"] },
  NKE: { add: ["Nike"] },
  KO: { add: ["Coca-Cola", "Coca Cola"] },
  PEP: { add: ["PepsiCo", "Pepsi"] },
  PG: { add: ["Procter & Gamble", "P&G"] },
  PM: { add: ["Philip Morris"] },
  MO: { add: ["Altria"] },
  T: { add: ["AT&T"] },
  VZ: { add: ["Verizon"] },
  TMUS: { add: ["T-Mobile"] },
  CMCSA: { add: ["Comcast"], brands: ["NBCUniversal"] },
  DIS: { add: ["Disney", "Walt Disney"] },
  NFLX: { add: ["Netflix"] },
  WBD: { add: ["Warner Bros Discovery", "Warner Bros. Discovery"] },
  PSKY: { add: ["Paramount Skydance", "Paramount"] },
  PLTR: { add: ["Palantir"] },
  ORCL: { add: ["Oracle Corp", "Oracle Corporation"], ambiguous: ["Oracle"] },
  IBM: { add: ["IBM"] },
  CSCO: { add: ["Cisco"] },
  INTC: { add: ["Intel"] },
  AMD: { add: ["AMD", "Advanced Micro Devices"] },
  AVGO: { add: ["Broadcom"] },
  QCOM: { add: ["Qualcomm"] },
  MU: { add: ["Micron"] },
  TXN: { add: ["Texas Instruments"] },
  AMAT: { add: ["Applied Materials"] },
  LRCX: { add: ["Lam Research"] },
  KLAC: { add: ["KLA Corp", "KLA Corporation"] },
  SMCI: { add: ["Super Micro", "Supermicro", "Super Micro Computer"] },
  DELL: { add: ["Dell"] },
  HPE: { add: ["Hewlett Packard Enterprise", "HPE"] },
  HPQ: { add: ["HP Inc"] },
  ANET: { add: ["Arista"] },
  CRM: { add: ["Salesforce"] },
  NOW: { add: ["ServiceNow"] },
  ADBE: { add: ["Adobe"] },
  WDAY: { add: ["Workday Inc"], ambiguous: ["Workday"] },
  CDNS: { add: ["Cadence Design"], ambiguous: ["Cadence"] },
  PANW: { add: ["Palo Alto Networks"], block: ["Palo Alto"] },
  CRWD: { add: ["CrowdStrike"] },
  FTNT: { add: ["Fortinet"] },
  UBER: { add: ["Uber"] },
  ABNB: { add: ["Airbnb"] },
  BKNG: { add: ["Booking Holdings", "Booking.com"] },
  BA: { add: ["Boeing"] },
  LMT: { add: ["Lockheed Martin", "Lockheed"] },
  RTX: { add: ["RTX Corp", "Raytheon"], ambiguous: ["RTX"], brands: ["Pratt & Whitney", "Collins Aerospace"] },
  MSI: { add: ["Motorola Solutions"], block: ["Motorola"] },
  TKO: { add: ["TKO Group"], block: ["TKO"] },
  APA: { add: ["APA Corp", "APA Corporation"], block: ["APA"] },
  PTC: { add: ["PTC Inc"], block: ["PTC"] },
  EQT: { add: ["EQT Corp", "EQT Corporation"], ambiguous: ["EQT"] },
  AES: { add: ["AES Corp", "AES Corporation"], block: ["AES"] },
  ROP: { add: ["Roper Technologies"], block: ["Roper"] },
  BEN: { add: ["Franklin Resources", "Franklin Templeton"], block: ["Franklin"] },
  NOC: { add: ["Northrop Grumman", "Northrop"] },
  GD: { add: ["General Dynamics"] },
  GE: { add: ["GE Aerospace"], block: ["GE"] },
  GEV: { add: ["GE Vernova"] },
  GEHC: { add: ["GE HealthCare", "GE Healthcare"] },
  CAT: { add: ["Caterpillar"] },
  DE: { add: ["Deere", "John Deere"] },
  MMM: { add: ["3M"] },
  HON: { add: ["Honeywell"] },
  UPS: { add: ["UPS", "United Parcel Service"] },
  FDX: { add: ["FedEx"] },
  UAL: { add: ["United Airlines"], block: ["United"] },
  DAL: { add: ["Delta Air Lines", "Delta Airlines"], ambiguous: ["Delta"] },
  LUV: { add: ["Southwest Airlines"], block: ["Southwest"] },
  XOM: { add: ["Exxon", "ExxonMobil", "Exxon Mobil"] },
  CVX: { add: ["Chevron", "Chevron Corp"] },
  COP: { add: ["ConocoPhillips"] },
  OXY: { add: ["Occidental"] },
  SLB: { add: ["SLB", "Schlumberger"] },
  HAL: { add: ["Halliburton"] },
  MPC: { add: ["Marathon Petroleum"], block: ["Marathon"] },
  DVN: { add: ["Devon Energy"], block: ["Devon"] },
  WMB: { add: ["Williams Companies", "Williams Cos"], block: ["Williams"] },
  FCX: { add: ["Freeport-McMoRan", "Freeport McMoRan"], block: ["Freeport"] },
  NEM: { add: ["Newmont"] },
  ALB: { add: ["Albemarle"] },
  NUE: { add: ["Nucor"] },
  LLY: { add: ["Eli Lilly", "Lilly"] },
  JNJ: { add: ["Johnson & Johnson", "J&J"] },
  MRK: { add: ["Merck"] },
  PFE: { add: ["Pfizer"] },
  ABBV: { add: ["AbbVie"] },
  BMY: { add: ["Bristol Myers Squibb", "Bristol-Myers Squibb", "Bristol Myers"] },
  MRNA: { add: ["Moderna"] },
  VRTX: { add: ["Vertex Pharmaceuticals"], block: ["Vertex"] },
  UNH: { add: ["UnitedHealth", "UnitedHealthcare"], brands: ["Optum"] },
  CVS: { add: ["CVS", "CVS Health"], brands: ["Aetna"] },
  ELV: { add: ["Elevance"] },
  CI: { add: ["Cigna"] },
  HUM: { add: ["Humana"] },
  CEG: { add: ["Constellation Energy"], block: ["Constellation"] },
  STZ: { add: ["Constellation Brands"], block: ["Constellation"] },
  VST: { add: ["Vistra"] },
  NEE: { add: ["NextEra"] },
  DUK: { add: ["Duke Energy"], block: ["Duke"] },
  SO: { add: ["Southern Company", "Southern Co"], block: ["Southern"] },
  D: { add: ["Dominion Energy"], block: ["Dominion"] },
  EIX: { add: ["Edison International", "Southern California Edison"], block: ["Edison"] },
  PCG: { add: ["PG&E"] },
  PRU: { add: ["Prudential Financial"], block: ["Prudential"] },
  PFG: { add: ["Principal Financial"], block: ["Principal"] },
  PGR: { add: ["Progressive Corp"], ambiguous: ["Progressive"] },
  TRV: { add: ["Travelers Companies", "Travelers Cos"], block: ["Travelers"] },
  HIG: { add: ["The Hartford", "Hartford Financial"], block: ["Hartford"] },
  BALL: { add: ["Ball Corp", "Ball Corporation"], block: ["Ball"] },
  WAT: { add: ["Waters Corp", "Waters Corporation"], block: ["Waters"] },
  FOXA: { add: ["Fox Corp", "Fox Corporation"], block: ["Fox"] },
  NWSA: { add: ["News Corp"] },
  MOS: { add: ["Mosaic Co"], block: ["Mosaic"] },
  GLW: { add: ["Corning Inc", "Corning Incorporated"], ambiguous: ["Corning"] },
  MNST: { add: ["Monster Beverage"], block: ["Monster"] },
  CARR: { add: ["Carrier Global"], block: ["Carrier"] },
  XYZ: { add: ["Block Inc", "Block, Inc."], brands: ["Square", "Cash App"], block: ["Block"] },
  CCL: { add: ["Carnival Corp", "Carnival Corporation", "Carnival Cruise"], ambiguous: ["Carnival"] },
  TPR: { add: ["Tapestry Inc"], ambiguous: ["Tapestry"] },
  FLEX: { add: ["Flex Ltd"], block: ["Flex"] },
  COHR: { add: ["Coherent Corp"], block: ["Coherent"] },
  ZBRA: { add: ["Zebra Technologies"], block: ["Zebra"] },
  EMR: { add: ["Emerson Electric"], ambiguous: ["Emerson"] },
  TYL: { add: ["Tyler Technologies"], block: ["Tyler"] },
  J: { add: ["Jacobs Solutions"], block: ["Jacobs"] },
  ROL: { add: ["Rollins Inc"], block: ["Rollins"] },
  OTIS: { add: ["Otis Worldwide", "Otis Elevator"], block: ["Otis"] },
  GEN: { add: ["Gen Digital"], brands: ["Norton"], block: ["Gen"] },
  EG: { add: ["Everest Group"], block: ["Everest"] },
  GL: { add: ["Globe Life"], block: ["Globe"] },
  L: { add: ["Loews Corp", "Loews Corporation"], block: ["Loews"] },
  DOW: { add: ["Dow Inc"], block: ["Dow"] },
  NDAQ: { add: ["Nasdaq Inc", "Nasdaq, Inc."], block: ["Nasdaq"] },
  SPGI: { add: ["S&P Global"], block: ["S&P"] },
  MSCI: { add: ["MSCI Inc"], block: ["MSCI"] },
  IT: { add: ["Gartner"] },
  KEY: { add: ["KeyCorp"] },
  RF: { add: ["Regions Financial"], block: ["Regions"] },
  CFG: { add: ["Citizens Financial"], block: ["Citizens"] },
  FITB: { add: ["Fifth Third"] },
  USB: { add: ["U.S. Bancorp", "US Bancorp"] },
  PNC: { add: ["PNC"] },
  COF: { add: ["Capital One"] },
  BNY: { add: ["BNY", "BNY Mellon", "Bank of New York Mellon"] },
  STT: { add: ["State Street"] },
  ICE: { add: ["Intercontinental Exchange", "NYSE parent"], block: ["ICE"] },
  CME: { add: ["CME Group"], block: ["CME"] },
  EXPE: { add: ["Expedia"] },
  MAR: { add: ["Marriott"] },
  HLT: { add: ["Hilton"] },
  RCL: { add: ["Royal Caribbean"] },
  NCLH: { add: ["Norwegian Cruise Line"], block: ["Norwegian"] },
  CMG: { add: ["Chipotle"] },
  YUM: { add: ["Yum Brands", "Yum! Brands"], brands: ["KFC", "Taco Bell", "Pizza Hut"] },
  DPZ: { add: ["Domino's Pizza", "Domino's"] },
  F: { add: ["Ford Motor", "Ford"] },
  GM: { add: ["General Motors", "GM"] },
  APP: { add: ["AppLovin"] },
  RDDT: { add: ["Reddit"] },
  DASH: { add: ["DoorDash"] },
  EQIX: { add: ["Equinix"] },
  DLR: { add: ["Digital Realty"] },
  AMT: { add: ["American Tower"] },
  O: { add: ["Realty Income"] },
  PSX: { add: ["Phillips 66"] },
  VLO: { add: ["Valero"] },
  KMI: { add: ["Kinder Morgan"] },
  CSX: { add: ["CSX"] },
  UNP: { add: ["Union Pacific"] },
  NSC: { add: ["Norfolk Southern"] },
  ADM: { add: ["ADM", "Archer-Daniels-Midland", "Archer Daniels Midland"] },
  BG: { add: ["Bunge"] },
  CTVA: { add: ["Corteva"] },
  CF: { add: ["CF Industries"] },
  TSN: { add: ["Tyson Foods", "Tyson"] },
  KHC: { add: ["Kraft Heinz"] },
  GIS: { add: ["General Mills"] },
  HSY: { add: ["Hershey"] },
  MDLZ: { add: ["Mondelez"] },
  STX: { add: ["Seagate"] },
  WDC: { add: ["Western Digital"] },
  SNDK: { add: ["Sandisk", "SanDisk"] },
  VRT: { add: ["Vertiv"] },
  ETN: { add: ["Eaton"] },
  PWR: { add: ["Quanta Services"], block: ["Quanta"] },
  MRVL: { add: ["Marvell"] },
  ON: { add: ["onsemi", "ON Semiconductor"] },
  NXPI: { add: ["NXP"] },
  ADI: { add: ["Analog Devices"] },
  MCHP: { add: ["Microchip Technology"], block: ["Microchip"] },
  ACN: { add: ["Accenture"] },
  INTU: { add: ["Intuit"] },
};

/**
 * Palabras comunes, apellidos y lugares: un alias GENERADO que coincida con una de ellas se trata
 * como ambiguo (necesita contexto) aunque no esté en los overrides.
 */
export const AMBIGUOUS_WORDS: ReadonlySet<string> = new Set([
  "target", "visa", "oracle", "block", "match", "ball", "pool", "waters", "fox", "carrier", "travelers", "hartford", "principal", "progressive",
  "southern", "williams", "devon", "marathon", "delta", "united", "apollo", "vertex", "edison", "duke", "dominion", "prudential", "mosaic",
  "corning", "constellation", "monster", "public", "global", "general", "american", "first", "key", "regions", "citizens", "gen", "dover",
  "cooper", "everest", "globe", "loews", "align", "axon", "flex", "coherent", "zebra", "tyler", "jacobs", "rollins", "otis", "ross", "carnival",
  "tapestry", "workday", "cadence", "emerson", "equity", "realty", "progress", "insulet",
  "welltower", "republic", "united rentals", "universal", "trade desk", "snap", "gap", "state", "state street", "northern", "southwest", "keysight",
  "mid america", "essex", "camden", "federal", "regency", "simon", "ventas", "vici", "iron", "casey's", "erie", "hubbell", "pentair", "xylem",
  "quest", "henry", "schein", "booking", "franklin", "news", "dow", "nasdaq", "tko", "apa", "ptc", "motorola", "roper", "cooper", "dover", "align",
]);

/**
 * Contextos que ANULAN un alias aunque sea seguro (homónimos frecuentes en noticias).
 * Clave: alias exacto; valor: patrón que, si aparece en el texto, descarta la coincidencia.
 */
export const ALIAS_EXCLUSIONS: Readonly<Record<string, RegExp>> = {
  Amazon: /amazon(?:'s)? (?:rainforest|river|basin|jungle|region|forest)|deforestation|indigenous/i,
  Apple: /apple (?:pie|orchard|orchards|juice|cider|growers|harvest|tree)s?|big apple/i,
  Ford: /(?:harrison|gerald|doug|tom|henry) ford|ford foundation|premier ford/i,
  Chevron: /chevron (?:deference|doctrine|decision|precedent)/i,
  Delta: /delta (?:variant|smelt|region|state)|niger delta|mekong delta|river delta/i,
  Target: /inflation target|price target|target(?:ed|ing)? (?:rate|range)/i,
  Meta: /meta-?analysis|metadata/i,
  RTX: /\b(geforce|nvidia|amd)\s+rtx\b|\brtx\s*\d{3,4}\b|\brtx\s+(pro|on|off)\b/i,
  Oracle: /oracle of omaha/i,
};

/** Contexto de empresa para alias ambiguos. */
export const COMPANY_CONTEXT = /\b(shares?|stock|stocks|inc\.?|corp\.?|company|companies|ceo|cfo|earnings|revenue|revenues|profit|quarter|quarterly|sales|investors?|analysts?|nyse|nasdaq|retailer|chain|stores|deal|acquir\w*|guidance|results|outlook|valuation|layoffs|lawsuit|sued|merger|buyback|dividend|ipo|brand|customers|market share|executive|chief|board|buys?|sells?|cuts?|jobs|plants?|factory|production|output|launch\w*|unveil\w*|deal|partners?|stake|bid|rival\w*)\b/i;

/**
 * Tickers que NO se aceptan como palabra suelta en el texto (son palabras, abreviaturas o
 * coinciden con índices): solo cuentan como $CASHTAG, "(NYSE: X)" o entre paréntesis.
 */
export const BARE_TICKER_BLOCK: ReadonlySet<string> = new Set([
  "ALL", "ARE", "CAT", "COST", "DAY", "DOW", "FAST", "HAS", "ICE", "KEY", "KEYS", "LOW", "MAR", "NOW", "PEG", "TAP", "TEL", "TECH", "WELL", "WAT",
  "BALL", "COO", "COR", "FIX", "FLEX", "EXE", "GEN", "AMP", "USB", "HIG", "CEO", "CFO", "IPO", "ETF", "GDP", "CPI", "FED", "SEC", "EPS", "USA",
  "APP", "DASH", "HOOD", "COIN", "MSCI", "CSX", "IBM", "CVS", "AMD", "UPS", "SLB", "ADM", "BNY", "KKR", "PNC", "NXP", "HPE", "RTX", "AES", "CDW",
  "EOG", "IQV", "NRG", "NVR", "PTC", "UDR", "BXP", "TKO", "CRH", "FDS", "LIN", "ROP", "MET", "EQT", "LEN", "DHI", "EXC", "EXR", "INVH", "VICI",
  "OTIS", "UBER", "DELL", "ANET", "PLTR", "META", "TSLA", "NVDA", "AAPL", "MSFT", "AMZN", "GOOGL", "GOOG", "AVGO", "ORCL", "INTC", "QCOM",
]);

/**
 * Nota: los tickers de la segunda mitad de BARE_TICKER_BLOCK (IBM, AMD, NVDA…) SÍ se reconocen: ya
 * tienen alias explícito con el mismo texto, así que no hace falta la vía de ticker suelto (y se evita
 * contarlos dos veces). La vía de ticker suelto queda para tickers de ≥3 letras sin alias propio.
 */
export const GENERIC_NAME_SUFFIXES = /\s+(?:inc\.?|incorporated|corporation|corp\.?|company|co\.?|companies|holdings?|group|plc|limited|ltd\.?|n\.v\.|s\.a\.|& co\.?|and company)$/i;
export const DESCRIPTOR_SUFFIXES = /\s+(?:technologies|technology|systems|international|global|worldwide|enterprises?|solutions|industries|brands|networks|labs|laboratories|platforms|entertainment|resources|markets|financial group|financial services)$/i;
