"use client";

import Link from "next/link";
import type { ClaimKind, ConfidenceBreakdown, ImpactDirection, NewsEvent } from "@/domain/news";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/cn";
import type { NodeChip } from "@/services/news";
import { useI18n } from "@/i18n/provider";
import { enumLabel } from "@/i18n/messages";
import { formatRelativeTime } from "@/lib/format";
import { classificationLabel } from "@/i18n/classification";

/**
 * Primitivas visuales de la capa de inteligencia. Regla: el usuario nunca debe confundir un HECHO con
 * una INFERENCIA del sistema. Cada afirmación lleva su tipo:
 *   SOURCE BASED (medios) · OFFICIAL (fuente primaria) · REAL (datos de MarketRadar) · INFERRED · AI · UNKNOWN
 */
const CLAIM: Record<ClaimKind, { label: string; variant: "official" | "neutral" | "positive" | "inferred" | "ai" | "outline"; title: string }> = {
  FACT: { label: "Official", variant: "official", title: "Fact from an official primary source (SEC EDGAR, central bank, statistics agency)" },
  SOURCE_CLAIM: { label: "Source based", variant: "neutral", title: "What a media source reports — attributed, may be incomplete or wrong" },
  MARKET_DATA: { label: "Real data", variant: "positive", title: "Calculated by MarketRadar from its real data (Alpaca prices, SEC fundamentals, synthetic indices)" },
  INFERENCE: { label: "Inferred", variant: "inferred", title: "Relationship inferred by MarketRadar's rules and curated graph — not a reported fact" },
  AI_INTERPRETATION: { label: "AI", variant: "ai", title: "Interpretation generated by an AI model, validated against the cited evidence" },
  UNKNOWN: { label: "Unknown", variant: "outline", title: "Not enough evidence — MarketRadar does not guess" },
};

export function ClaimKindBadge({ kind }: { kind: ClaimKind }) {
  const { locale } = useI18n();
  const labels: Record<ClaimKind, { label: string; title: string }> = locale === "es" ? {
    FACT: { label: "Oficial", title: "Hecho de una fuente primaria oficial (SEC EDGAR, banco central u organismo estadístico)" },
    SOURCE_CLAIM: { label: "Según fuentes", title: "Información publicada por un medio; se atribuye y puede ser incompleta o incorrecta" },
    MARKET_DATA: { label: "Datos reales", title: "Calculado por MarketRadar a partir de sus datos reales (precios Alpaca, fundamentales SEC e índices sintéticos)" },
    INFERENCE: { label: "Inferido", title: "Relación inferida por las reglas y el grafo de MarketRadar; no es un hecho publicado" },
    AI_INTERPRETATION: { label: "IA", title: "Interpretación generada por un modelo de IA y contrastada con la evidencia citada" },
    UNKNOWN: { label: "Desconocido", title: "Evidencia insuficiente; MarketRadar no hace conjeturas" },
  } : Object.fromEntries(Object.entries(CLAIM).map(([key, value]) => [key, { label: value.label, title: value.title }])) as Record<ClaimKind, { label: string; title: string }>;
  const c = { ...CLAIM[kind], ...labels[kind] };
  return (
    <Badge variant={c.variant} title={c.title}>
      {c.label}
    </Badge>
  );
}

const CONF_LABEL = (score: number) => (score >= 0.72 ? "High" : score >= 0.5 ? "Medium" : "Low");

export function confidenceTitle(c: ConfidenceBreakdown, locale: "es" | "en" = "en"): string {
  if (locale === "es") return [
    `Confianza ${Math.round(c.score * 100)}/100 (${c.score >= 0.72 ? "Alta" : c.score >= 0.5 ? "Media" : "Baja"}) — cuánto confiamos en que el evento ocurrió como se describe y en que las entidades son correctas. No predice precios.`,
    `Calidad de fuente ${Math.round(c.sourceQuality * 100)} · Corroboración ${Math.round(c.corroboration * 100)} · Coincidencia de entidad ${Math.round(c.entityMatch * 100)} · Recencia ${Math.round(c.recency * 100)} · Clasificación ${Math.round(c.classification * 100)} · Acuerdo ${Math.round(c.agreement * 100)} · Certeza ${Math.round((c.eventCertainty ?? 0) * 100)}`,
    ...c.notes,
  ].join("\n");
  return [
    `Confidence ${Math.round(c.score * 100)}/100 (${CONF_LABEL(c.score)}) — how much we trust that the event happened as described and entities are right. Not a price prediction.`,
    `Source quality ${Math.round(c.sourceQuality * 100)} · Corroboration ${Math.round(c.corroboration * 100)} · Entity match ${Math.round(c.entityMatch * 100)} · Recency ${Math.round(c.recency * 100)} · Classification ${Math.round(c.classification * 100)} · Agreement ${Math.round(c.agreement * 100)} · Certainty ${Math.round((c.eventCertainty ?? 0) * 100)}`,
    ...c.notes,
  ].join("\n");
}

export function ConfidenceMeter({ confidence, className }: { confidence: ConfidenceBreakdown; className?: string }) {
  const { locale } = useI18n();
  const pct = Math.round(confidence.score * 100);
  const label = locale === "es" ? (confidence.score >= 0.72 ? "Alta" : confidence.score >= 0.5 ? "Media" : "Baja") : CONF_LABEL(confidence.score);
  return (
    <span className={cn("inline-flex items-center gap-1.5 text-[10px] text-fg-muted", className)} title={confidenceTitle(confidence, locale)}>
      <span role="meter" aria-valuemin={0} aria-valuemax={100} aria-valuenow={pct} aria-label={`${locale === "es" ? "Confianza" : "Confidence"} ${pct} ${locale === "es" ? "de" : "of"} 100`} className="relative h-1 w-10 overflow-hidden rounded-full bg-surface-hover">
        <span className={cn("absolute inset-y-0 left-0 rounded-full", label === "High" ? "bg-fg-secondary" : label === "Medium" ? "bg-fg-muted" : "bg-warning")} style={{ width: `${pct}%` }} />
      </span>
      <span className="font-mono">{pct}</span>
      <span className="uppercase">{label}</span>
    </span>
  );
}

const DIR: Record<ImpactDirection, { symbol: string; cls: string }> = {
  potential_positive: { symbol: "↗", cls: "text-positive" },
  potential_negative: { symbol: "↘", cls: "text-negative" },
  mixed_uncertain: { symbol: "↔", cls: "text-fg-secondary" },
};

export function DirectionMark({ direction, label }: { direction: ImpactDirection; label?: string }) {
  const { locale } = useI18n();
  const d = DIR[direction];
  const translated = enumLabel(locale, direction) || label || "";
  return (
    <span className={cn("inline-flex items-center gap-1 whitespace-nowrap", d.cls)} title={`${translated} — ${locale === "es" ? "relación potencial, no una predicción" : "potential relationship, not a prediction"}`}>
      <span aria-hidden>{d.symbol}</span>
      <span className="text-[10px] font-semibold uppercase">{translated.replace(/^Potential /, "")}</span>
    </span>
  );
}

const CHANNEL_LABEL: Record<string, string> = { DIRECT: "Direct", SECOND_ORDER: "2nd order", MACRO: "Macro", SUPPLY_CHAIN: "Supply chain" };
export function ChannelTag({ channel }: { channel: string }) {
  const { locale } = useI18n();
  const spanish: Record<string, string> = { DIRECT: "Directo", SECOND_ORDER: "2.º orden", MACRO: "Macro", SUPPLY_CHAIN: "Cadena de suministro" };
  return <span className="rounded-[3px] border border-border px-1 text-[9px] font-semibold tracking-wide text-fg-muted uppercase">{locale === "es" ? spanish[channel] ?? channel : CHANNEL_LABEL[channel] ?? channel}</span>;
}

/** Chip de entidad: DIRECT (mencionada) con borde sólido; INFERRED con borde discontinuo y color de inferencia. */
export function EntityChip({ chip, short }: { chip: NodeChip; short?: string }) {
  const { locale } = useI18n();
  const inferred = chip.relation === "INFERRED";
  const label = classificationLabel(locale, chip.label);
  const method = locale === "es" ? ({ alias: "alias", alias_context: "alias contextual", cik: "código CIK", keyword: "palabra clave", classification: "clasificación", macro_scope: "ámbito macro", event_rule: "regla de evento" } as Record<string, string>)[chip.method] ?? chip.method : chip.method;
  const evidence = locale !== "es" ? chip.evidence : (() => {
    if (chip.method === "classification") {
      const match = chip.evidence.match(/^(.*?) is classified in GICS (.+)$/);
      if (match) return `${match[1]} tiene la clasificación GICS ${classificationLabel(locale, match[2] ?? "")}`;
    }
    if (chip.method === "macro_scope") {
      const generated: Record<string, string> = {
        "Central bank events can affect the overall market": "Los eventos de bancos centrales pueden afectar al mercado en general",
        "Growth & activity events can affect the overall market": "Los eventos de crecimiento y actividad pueden afectar al mercado en general",
        "Rates & bonds events can affect the overall market": "Los eventos de tipos y bonos pueden afectar al mercado en general",
        "Trade & tariffs events can affect the overall market": "Los eventos de comercio y aranceles pueden afectar al mercado en general",
        "Growth & activity events relate to Economic growth": "Los eventos de crecimiento y actividad están relacionados con el crecimiento económico",
        "AI & data centers events relate to AI demand": "Los eventos de IA y centros de datos están relacionados con la demanda de IA",
      };
      if (generated[chip.evidence]) return generated[chip.evidence];
    }
    return chip.evidence.replace(/ · in (\d+)\/(\d+) articles/g, " · en $1/$2 artículos");
  })();
  const title = `${label} — ${inferred ? (locale === "es" ? "INFERIDO" : "INFERRED") : (locale === "es" ? "MENCIÓN DIRECTA" : "DIRECT MENTION")} (${method}, ${locale === "es" ? "confianza" : "confidence"} ${Math.round(chip.confidence * 100)}): ${evidence}`;
  const cls = cn(
    "inline-flex max-w-44 items-center gap-1 truncate rounded-[3px] border px-1.5 py-px text-[10px] leading-4",
    inferred ? "border-dashed border-inferred/50 text-inferred" : "border-border-strong text-fg-secondary",
    chip.href && "hover:border-accent hover:text-accent",
  );
  const content = (
    <>
      {inferred && <span aria-hidden className="text-[9px]">≈</span>}
      <span className={cn(chip.kind === "company" && "font-mono")}>{short ?? label}</span>
    </>
  );
  return chip.href ? (
    <Link href={chip.href} className={cls} title={title}>
      {content}
    </Link>
  ) : (
    <span className={cls} title={title}>
      {content}
    </span>
  );
}

const STATUS: Record<NewsEvent["status"], { label: string; variant: "accent" | "neutral" | "outline" }> = {
  developing: { label: "Developing", variant: "accent" },
  active: { label: "Active", variant: "neutral" },
  stale: { label: "Older", variant: "outline" },
};

export function StatusBadge({ status }: { status: NewsEvent["status"] }) {
  const { locale } = useI18n();
  const s = STATUS[status];
  const label = locale === "es" ? ({ developing: "En desarrollo", active: "Activo", stale: "Anterior" } as const)[status] : s.label;
  const title = locale === "es" ? "En desarrollo: detectado hace menos de 6 h · Activo: artículos nuevos en las últimas 48 h · Anterior: sin cobertura nueva durante 48 h" : "Developing: first seen < 6 h ago · Active: new articles in the last 48 h · Older: no new coverage for 48 h";
  return (
    <Badge variant={s.variant} title={title}>
      {label}
    </Badge>
  );
}

export function timeAgo(iso: string, now: Date = new Date()): string {
  const diff = Math.max(0, now.getTime() - Date.parse(iso));
  const m = Math.round(diff / 60_000);
  if (m < 60) return `${Math.max(1, m)}m ago`;
  const h = Math.round(m / 60);
  if (h < 48) return `${h}h ago`;
  return `${Math.round(h / 24)}d ago`;
}

export function TimeAgo({ iso, now }: { iso: string; now?: Date }) {
  const { locale } = useI18n();
  return (
    <time dateTime={iso} title={new Date(iso).toUTCString()} className="whitespace-nowrap">
      {formatRelativeTime(iso, now, locale)}
    </time>
  );
}

/** Leyenda de tipos de información (se muestra en World Pulse y en fichas). */
export function ClaimLegend() {
  const { locale, messages } = useI18n();
  return (
    <div className="flex flex-wrap items-center gap-1.5 text-[10px] text-fg-muted">
      <span>{messages.intelligence.legend}:</span>
      {(["FACT", "SOURCE_CLAIM", "MARKET_DATA", "INFERENCE", "AI_INTERPRETATION", "UNKNOWN"] as ClaimKind[]).map((k) => (
        <ClaimKindBadge key={k} kind={k} />
      ))}
      <span className="inline-flex items-center gap-1">
        <span className="rounded-[3px] border border-border-strong px-1">{messages.common.direct}</span>/<span className="rounded-[3px] border border-dashed border-inferred/50 px-1 text-inferred">≈ {messages.common.inferred}</span> {locale === "es" ? "entidad" : "entity"}
      </span>
    </div>
  );
}
